[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SOLANA_RPC_URL = "https://api.devnet.solana.com"
  NEXT_PUBLIC_SOLANA_NETWORK = "devnet"
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false 