[features]
seeds = false
skip-lint = false

[programs.localnet]
roast_token = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
roast_nft = "RoaStnFttMhnLXVxY5Lz2RXRxUWzjXtjuYP3oTNro4R"

[programs.devnet]
roast_token = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
roast_nft = "RoaStnFttMhnLXVxY5Lz2RXRxUWzjXtjuYP3oTNro4R"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
deploy-token = "anchor deploy --program-name roast_token"
deploy-nft = "anchor deploy --program-name roast_nft" 